### ISSUE TITLE
deep dark sculk generating above ground in the Chasm biome

### ISSUE THREAD

**Issue by hydrangea72** [jaskarth/ecotones#38]
I was testing out the mod, and i found a biome that had sculk generating above ground in a section of it, and i'm pretty sure it is not intentional so i'm reporting it here.
![Screen Shot 2023-07-04 at 11 53 47 PM](https://github.com/jaskarth/ecotones/assets/63913368/8ca086f6-9a8e-432b-926a-76218341ed3d)

**Comment by jaskarth** [comment]
This has been fixed, thanks!
